class EventNames():
    SOCKET_BROAD_CAST = 'SOCKET_BROAD_CAST'

    CAMERA_IS_STREAMING = 'CAMERA_IS_STREAMING'
    CAMERA_START_STREAMING = 'CAMERA_START_STREAMING'
    CAMERA_STOP_STREAMING = 'CAMERA_STOP_STREAMING'
    CAMERA_GET_STATUS = 'CAMERA_GET_STATUS'

    MOVING = 'MOVING'

    SYSTEM_RESTART = 'SYSTEM_RESTART'

    CAMERA_PANTILT_MOVE = 'CAMERA_PANTILT_MOVE'
    CAMERA_PANTILT_STOP= 'CAMERA_PANTILT_STOP'

    ULTRASONIC_START_MEAUSRE = 'ULTRASONIC_START_MEAUSRE'
    ULTRASONIC_STOP_MEAUSRE = 'ULTRASONIC_STOP_MEAUSRE'
    ULTRASONIC_ON_MEAUSRE = 'ULTRASONIC_ON_MEAUSRE'
        