class EventNames():
    SOCKET_BROAD_CAST = 'SOCKET_BROAD_CAST'

    CAMERA_IS_STREAMING = 'CAMERA_IS_STREAMING'
    CAMERA_START_STREAMING = 'CAMERA_START_STREAMING'
    CAMERA_STOP_STREAMING = 'CAMERA_STOP_STREAMING'

    MOVING = 'MOVING'
        